# Generated by Django 4.2.6 on 2023-10-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img',
        ),
    ]
